# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platform"
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(673, 459)
        self.btnSign = QtWidgets.QPushButton(Dialog)
        self.btnSign.setGeometry(QtCore.QRect(150, 330, 88, 34))
        self.btnSign.setObjectName("btnSign")
        self.btnVerify = QtWidgets.QPushButton(Dialog)
        self.btnVerify.setGeometry(QtCore.QRect(430, 330, 88, 34))
        self.btnVerify.setObjectName("btnVerify")
        self.txtSign = QtWidgets.QPlainTextEdit(Dialog)
        self.txtSign.setGeometry(QtCore.QRect(150, 210, 371, 101))
        self.txtSign.setObjectName("txtSign")
        self.txtInfo = QtWidgets.QPlainTextEdit(Dialog)
        self.txtInfo.setGeometry(QtCore.QRect(150, 90, 371, 101))
        self.txtInfo.setObjectName("txtInfo")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 20, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnGenerateKeys = QtWidgets.QPushButton(Dialog)
        self.btnGenerateKeys.setGeometry(QtCore.QRect(417, 30, 101, 34))
        self.btnGenerateKeys.setObjectName("btnGenerateKeys")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 91, 18))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(50, 210, 91, 18))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnSign.setText(_translate("Dialog", "Sign"))
        self.btnVerify.setText(_translate("Dialog", "Verify"))
        self.label.setText(_translate("Dialog", "ECC CIPHER"))
        self.btnGenerateKeys.setText(_translate("Dialog", "Generate keys"))
        self.label_2.setText(_translate("Dialog", "Information"))
        self.label_3.setText(_translate("Dialog", "Signature"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
