# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rsacipher(object):
    def setupUi(self, rsacipher):
        rsacipher.setObjectName("rsacipher")
        rsacipher.resize(1116, 513)
        self.centralwidget = QtWidgets.QWidget(rsacipher)
        self.centralwidget.setObjectName("centralwidget")
        self.lblTitle = QtWidgets.QLabel(self.centralwidget)
        self.lblTitle.setGeometry(QtCore.QRect(0, 0, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.lblTitle.setFont(font)
        self.lblTitle.setObjectName("lblTitle")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 40, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(530, 40, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 190, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(100, 370, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(380, 370, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.txt_plain_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_plain_text.setGeometry(QtCore.QRect(70, 80, 421, 111))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.txt_cipher_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_cipher_text.setGeometry(QtCore.QRect(70, 240, 421, 111))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.txt_info = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_info.setGeometry(QtCore.QRect(590, 80, 421, 111))
        self.txt_info.setObjectName("txt_info")
        self.txt_sign = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_sign.setGeometry(QtCore.QRect(590, 240, 421, 111))
        self.txt_sign.setObjectName("txt_sign")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(530, 200, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btn_sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sign.setGeometry(QtCore.QRect(610, 370, 75, 23))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_verify = QtWidgets.QPushButton(self.centralwidget)
        self.btn_verify.setGeometry(QtCore.QRect(910, 370, 75, 23))
        self.btn_verify.setObjectName("btn_verify")
        self.btn_gen_keys = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gen_keys.setGeometry(QtCore.QRect(530, 10, 75, 23))
        self.btn_gen_keys.setObjectName("btn_gen_keys")
        rsacipher.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(rsacipher)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 21))
        self.menubar.setObjectName("menubar")
        rsacipher.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(rsacipher)
        self.statusbar.setObjectName("statusbar")
        rsacipher.setStatusBar(self.statusbar)

        self.retranslateUi(rsacipher)
        QtCore.QMetaObject.connectSlotsByName(rsacipher)

    def retranslateUi(self, rsacipher):
        _translate = QtCore.QCoreApplication.translate
        rsacipher.setWindowTitle(_translate("rsacipher", "Caesar cipher"))
        self.lblTitle.setText(_translate("rsacipher", "RSA CIPHER"))
        self.label.setText(_translate("rsacipher", "Plain text:"))
        self.label_2.setText(_translate("rsacipher", "Information:"))
        self.label_3.setText(_translate("rsacipher", "Cipher text:"))
        self.btn_encrypt.setText(_translate("rsacipher", "Encrypt"))
        self.btn_decrypt.setText(_translate("rsacipher", "Decrypt"))
        self.label_4.setText(_translate("rsacipher", "Signature:"))
        self.btn_sign.setText(_translate("rsacipher", "Sign"))
        self.btn_verify.setText(_translate("rsacipher", "Verify"))
        self.btn_gen_keys.setText(_translate("rsacipher", "Generate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    rsacipher = QtWidgets.QMainWindow()
    ui = Ui_rsacipher()
    ui.setupUi(rsacipher)
    rsacipher.show()
    sys.exit(app.exec_())
